<div class="text-box">


# Implications, Limitations, and Future Studies


</div> 


<div class="text-box">


## Implications


The findings of this study could carry significant implications for policymakers, educational institutions, community organizations, and future research to address economic disparities and educational outcomes within different racial identities under the overarching Latine identity. 




1) To improve post-secondary achievement rates, especially in communities with higher Black-Latine/Hispanic populations, there is a need for comprehensive support programs. Support programs may include mentorship programs, academic advising, financial aid counseling, and initiatives that address barriers such as transportation for this specific community. Aditionally, educational institutions should collaborate with local organizations to create pathways for students from underrepresented communities, as well as approach Latine communities with a more nuanced understanding of the different racial experiences within the Latine community to better serve Latine students. Partnerships can facilitate access to resources, internships, and career opportunities that enhance educational outcomes.


2) The finding that the presence of post-secondary institutions does not significantly impact achievement rates indicates that mere proximity to educational facilities is insufficient. Implying that educational instiutions are doing little to support their local communities. Educational institutions should engage in active outreach and provide support services to effectively influence post-secondary attainment in their surrounding areas. 



</div>

<div class="text-box">

## Limitations

The current project was limited by multiple factors

1) More intricate statistical analysis: My project compared differences within census tracts using simple calculations (mean averages), future studies should use more intricate statistical measures to better analyze the correlation between living within a census tract with a post-secondary building and my chosen demographic variables. Unfortunately, my statistical training is limited, and when initially trying to incorporate a basic Altair correlation heatmap, I found this approach to not clearly define which variables were decreasing and which was increasing within the **slight** negative correlations that would appear. 

2) The method in which I distinguished Black-Latines, and White-Latines may be limited by the presence of other demographics that may influence trends within the chosen census tracts. Future studies should do an additional analysis of seperate demographic variables to analyze how these correlate within census tracts that have more Black-Latines than White-Latines and vice-versa. 

3) Using more sophisticated statistical analysis (such as Moran's I) to test the influence of not only living within a census tract that has a post-secondary insititution, but also the effect of living in a census tract that neighboor's a post-secondary instiution. 



</div> 

<div class="text-box">

## Future Studies

Future studies should 

1) Utilize measures like Moran’s I to assess the degree of spatial autocorrelation in  data, thereby understanding how proximity to certain features (e.g., post-secondary institutions) affects economic and educational outcomes.

2) Expand the analysis to other cities that have a more predominant Black-Latine population (such as New York), to analyze if similar trends exist in other geographic locations. 

3) Incorporate more sophisticated statistical methods such as multiple regression analysis, factor analysis, or structural equation modeling to examine the interplay between various socioeconomic and demographic variables to illustrate a better picture of the most influential factors contributing to income disparities and educational outcomes within different census tracts.


