

<div class="text-box">
# Part 2: Correlation Between Demographics and Post-Secondary Buildings Per Tract
</div>

<div class="text-box">
**Goals of Part 2**

Part 2 is Dedicated to Answering the Following Research Question 

2) What is the correlation between living in the same tract as post-secondary school building(s) and post-secondary achievement rate (Associate and/or Bachelors Degree) 
       
       a) How does this vary across racial/ethnic demographics, 
        and Median Household Income. 

</div>

<div class="text-box">

**What you'll see in Part 2**

1) Downloading post-secondary building data geojson from OpenDataPhilly

2) Merging building geojson with original "Identity_Per_Tract" dataframe from Part 1

3) Creation of an interactive widget and panel that allows users to scroll through different census tracts,
and analyze the demographics of each tract that contain 1 or more post-secondary building. 

4) Statistical analysis (Correlation Coefficient, Standard Error, & P-Value) of demographic variables 
and school buildings per census tract

5) Creation of a correlation heatmap with hvplot with a touchtip that shows the correlation, standard error, and p-value
between the relationships of all demographic variables and school buildings per tract/ 

</div>



